### PR TITLE
all: use errors.New() which has no param instead of fmt.Errorf()

### PR DESCRIPTION
**Pull request by yasyzb**
use errors.New() which has no param instead of fmt.Errorf()

### CODE REVIEW

**Review by haraldh — APPROVED** [review]

**Comment by haraldh** [comment]
oh, please sign your commits (after setting up the keys in github)

**Review by haraldh — CHANGES_REQUESTED** [review]
Please sign the commit and repush --force

**Comment by yasyzb** [comment]
> Please sign the commit and repush --force

OK, I have solved the conflicts, and repushed.

**Comment by yasyzb** [comment]
> Please sign the commit and repush --force

Thank you, I have sign commit and repushed.

**Comment by haraldh** [comment]
please rebase onto current origin/main.. no need for merge commits

**Comment by yasyzb** [comment]
> please rebase onto current origin/main.. no need for merge commits

thank you, I have rebased main.

**Review by haraldh — APPROVED** [review]

**Comment by haraldh** [comment]
Thank you!

**Pull request merged**
